name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install system dependencies for desktop app
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            build-essential \
            git \
            libyaml-dev \
            pkg-config \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libatk1.0-dev \
            libgdk-pixbuf2.0-dev \
            libglib2.0-dev

      - name: Test Ruby syntax
        run: |
          ruby -c script/grocery_sorter.rb
          ruby -c script/setup.rb
          ruby -c app/services/google_auth_service.rb
          ruby -c app/services/google_docs_service.rb
          ruby -c app/services/ollama_service.rb

      - name: Test Makefile syntax
        run: make -n help

      - name: Test installation script syntax
        run: bash -n install.sh

      - name: Run basic functionality test
        run: |
          # Test that the app can be loaded without errors
          ruby -e "
            require 'bundler/setup'
            require_relative 'script/grocery_sorter'
            puts '✅ App loads successfully'
          "

      - name: Test setup wizard (dry run)
        run: |
          # Test setup script can be loaded
          ruby -e "
            require 'bundler/setup'
            require_relative 'script/setup'
            puts '✅ Setup script loads successfully'
          "
